export const OTELLER = [
  { id: 1, ad: 'Antalya Palace', konum: 'Lara, Antalya', fiyat: 3500, resim: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800', aciklama: 'Akdeniz’in turkuaz sularına sıfır konumuyla Antalya Palace, ultra lüks her şey dahil konsepti, geniş aquaparkları ve dünya mutfağından lezzetler sunan restoranlarıyla aileler için unutulmaz bir tatil sunar.' },
  { id: 2, ad: 'Istanbul Bosphorus', konum: 'Beşiktaş, İstanbul', fiyat: 5000, resim: 'https://www.fourseasons.com/alt/img-opt/~75.430.0,0000-0,0000-2250,6667-1688,0000/publish/content/dam/fourseasons/images/web/BOP/BOP_1818_original.jpg', aciklama: 'Tarihi yarımadanın ve Boğaz’ın büyüleyici manzarasını odanıza taşıyan otel, saray ihtişamını modern teknolojiyle birleştirerek Beşiktaş’ın kalbinde 5 yıldızlı bir konfor og eşsiz bir spa deneyimi vaat ediyor.' },
  { id: 3, ad: 'Bodrum Blue Hotel', konum: 'Yalıkavak, Muğla', fiyat: 4200, resim: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800', aciklama: 'Ege’nin serin sularına açılan özel iskelesi ve bembeyaz Bodrum mimarisiyle huzurun adresi olan tesis, Yalıkavak Marina’ya komşu konumu ve gün batımı manzaralı şık restoranıyla dinamik bir tatil atmosferi sunuyor.' },
  { id: 4, ad: 'Kapadokya Cave', konum: 'Göreme, Nevşehir', fiyat: 2800, resim: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/f1/c2/cb/caption.jpg?w=900&h=500&s=1', aciklama: 'Binlerce yıllık peri bacalarının içine oyulmuş otantik mağara odalarda tarihin dokusunu hissedin; sabahın ilk ışıklarında gökyüzünü süsleyen balonları izleyebileceğiniz terasıyla masalsı bir konaklama deneyimi yaşayın.' },
  { id: 5, ad: 'Uludağ Ski Resort', konum: '2. Bölge, Uludağ', fiyat: 3100, resim: 'https://cdn.tatilsepeti.com/Files/Images/Tesis/05673/1050X700/tsr05673639077058353301747.jpg', aciklama: 'Pistlere doğrudan erişim imkanı sağlayan otelimiz, kayak sonrası şömine başında sıcak çikolata keyfi yapabileceğiniz dağ evi mimarisi ve ısıtmalı kapalı havuzuyla kış tatilinin en popüler ve konforlu rotasıdır.' },
  { id: 6, ad: 'Fethiye Marina Hotel', konum: 'Merkez, Fethiye', fiyat: 2900, resim: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800', aciklama: 'Fethiye’nin simgesi marinaya birkaç adım uzaklıkta yer alan butik otelimiz, modern dekorasyonu, tekne turlarına erişim kolaylığı ve kordon boyundaki restoranlara yakınlığıyla deniz severler için ideal bir seçimdir.' },
  { id: 7, ad: 'Efes Antik Pansiyon', konum: 'Selçuk, İzmir', fiyat: 1500, resim: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/02/58/c4/natureland-efes-pension.jpg?w=900&h=500&s=1', aciklama: 'Antik kentin mistik havasında begonvillerle çevrili avlusuyla samimi bir aile işletmesi; bahçedeki zeytin ağaçları altında ev yapımı reçellerle güne başlayabileceğiniz bütçe dostu ve kültürel bir konaklama noktası.' },
  { id: 8, ad: 'Rize Yayla Evi', konum: 'Ayder, Rize', fiyat: 1800, resim: 'https://www.bungalov.com.tr/images/hotel/6193_v_922777.jpg', aciklama: 'Kaçkar Dağları’nın sisli zirvelerinde tamamen ahşap mimariyle inşa edilmiş bu ev, kuş sesleriyle uyanacağınız doğanın kalbinde Karadeniz’in taze havası ve yöresel yemekleriyle dijital detoks yapma fırsatı sunar.' },
  { id: 9, ad: 'Alaçatı Butik Otel', konum: 'Çeşme, İzmir', fiyat: 3800, resim: 'https://images.unsplash.com/photo-1525596662741-e94ff9f26de1?auto=format&fit=crop&w=800', aciklama: 'Taş sokaklara komşu bohem ve şık tasarımıyla ön plana çıkan otelimiz, antika mobilyalarla döşenmiş odaları ve Çeşme’nin hareketli hayatına yakınlığına rağmen bahçesinde sunduğu tam sükunetle fark yaratıyor.' },
  { id: 10, ad: 'Mardin Taş Saray', konum: 'Artuklu, Mardin', fiyat: 2500, resim: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLWa7S6qMCo2fWVXFzAoktw5vqmP8f-WBqjg&s', aciklama: 'Mezopotamya ovasına hakim bir tepede yer alan Taş Saray, yüksek tavanlı taş odaları, geleneksel el işçiliği süslemeleri ve gün batımını izleyebileceğiniz terasıyla misafirlerine binlerce yıllık bir tarih yolculuğu sunuyor.' },
  { id: 11, max_age: 120, ad: 'Pamukkale Thermal Resort', konum: 'Pamukkale, Denizli', fiyat: 2200, resim: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/87/49/38/richmond-pamukkale-thermal.jpg?w=900&h=500&s=1', aciklama: 'Travertenlerin yanı başında mineral bakımından zengin termal suları odanıza getiren tesisimiz, profesyonel spa olanakları ve sağlık odaklı mutfağıyla hem dinlenmek hem de yenilenmek isteyenlerin ilk tercihidir.' },
  { id: 12, ad: 'Safranbolu Konakları', konum: 'Merkez, Karabük', fiyat: 1700, resim: 'https://www.kurkcukonak.com/images/kurkcu-konak.jpg', aciklama: 'UNESCO listesindeki Safranbolu’da aslına uygun restore edilmiş 200 yıllık konaklarımızda ahşap işçiliği ve Safranbolu lokumuyla karşılandığınız samimi ortamda zamanda yolculuk yapacağınız bir deneyim sizi bekliyor.' },
  { id: 13, ad: 'Kaş Glamping', konum: 'Çukurbağ, Antalya', fiyat: 2000, resim: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800', aciklama: 'Kamp ruhunu lüks konforla buluşturan panoramik deniz manzaralı çadır odalarımız, doğaya uyumlu tasarımı, açık hava sineması ve sabah yoga seanslarıyla modern hayattan uzaklaşmak isteyenler için özel bir kaçış noktasıdır.' },
  { id: 14, ad: 'Bolu Abant Köşkü', konum: 'Abant Gölü, Bolu', fiyat: 3200, resim: 'https://cdn.tatilsepeti.com/Files/Images/Tesis/01484/1050X700/tsr01484638285741496354387.jpg', aciklama: 'Abant Gölü’nün tam kıyısında çam ormanlarıyla sarmalanmış bu özel köşk, kışın karlar altında romantik bir atmosfer, baharda ise göl kenarı yürüyüşleriyle dört mevsim huzur arayan doğa tutkunlarının tek adresidir.' }
];